version: 1.0.0.{build}
configuration: Release

image: Visual Studio 2017

pull_requests:
  do_not_increment_build_number: true
  
nuget:
  disable_publish_on_pr: true

branches:
  only:
  - master
  
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

before_build:
  - dotnet --version
  - dotnet restore ./src/Iso.Api.sln --verbosity m

build_script:
  - dotnet publish ./src/Iso.Api/Iso.Api.csproj

artifacts:
    - path: ./src/**/*.nupkg
      name: NuGet
