version: 1.0.0.{build}
configuration: Release

image: Visual Studio 2017

pull_requests:
  do_not_increment_build_number: true

nuget:
  disable_publish_on_pr: true

branches:
  only:
  - master

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

before_build:
    - dotnet --version

build:
    publish_azure: true

build_script:
    - dotnet build ./src/Iso.Api/Iso.Api.csproj --verbosity m --configuration Release
    - dotnet publish ./src/Iso.Api/Iso.Api.csproj --verbosity m --configuration Release --self-contained --runtime win-x64

after_build:
    7z a iso.zip %APPVEYOR_BUILD_FOLDER%\src\Iso.Api\bin\Release\netcoreapp2.1\win-x64\publish\

artifacts:
    - path: iso.zip
      name: IsoPublished

deploy:
    - provider: AzureAppServiceZipDeploy
      appservice_environment: false
      website: isodata
      username: $isodata
      password:
        secure: 1nkTq4LDACHVRjktkCBRP2HSlGswIi9IolYOnfouK2Q4wXr8SHo6ttMLmZfwfCyoNeELjmzWh0A6v0Ny9IJG2g==
